// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"gfDeomo/internal/model/entity"

	"github.com/gogf/gf/v2/net/ghttp"
)

type IArticle interface {
	Index(r *ghttp.Request, articles entity.Articles) bool
}

var localArticle IArticle

func Article() IArticle {
	if localArticle == nil {
		panic("implement not found for interface IArticle, forgot register?")
	}
	return localArticle
}

func RegisterArticle(i IArticle) {
	localArticle = i
}
