// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalArticlesDao is internal type for wrapping internal DAO implements.
type internalArticlesDao = *internal.ArticlesDao

// articlesDao is the data access object for table articles.
// You can define custom methods on it to extend its functionality as you wish.
type articlesDao struct {
	internalArticlesDao
}

var (
	// Articles is globally public accessible object for table articles operations.
	Articles = articlesDao{
		internal.NewArticlesDao(),
	}
)

// Fill with you ideas below.
