server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  graceful: true

logger:
  level : "all"
  stdout: true


database:
  default:
    type:  "mysql"
    link:  "root:123456@tcp(127.0.0.1:3307)/blog"





